# Site settings
baseurl = "https://enta1234.github.io/"
languageCode = "en-us"
title = "Chantatha.p"
theme = "hugo-minimalist-theme"


# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
disqusShortname = "enta1234"
# Enable gogle analytics by entering your tracking code
googleAnalytics = ""


[params]
    site_author = "Chantatha Polsamak"
    site_description = "The awesome blog of John Doe."
    location = "bangkok thailand"

    # Link custom assets relative to /static
    avatar = "img/profile-image.png"
    header_background = "img/desk.jpg"
    header_title = "Full Stack Web Developer & DevOps"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = ""
    facebook  = ""
    linkedin  = ""
    behance   = ""
    dribbble  = ""
    instagram = "chy.noi"
    github    = "enta1234"
    gplus     = ""